// Generated by CoffeeScript 1.3.1
(function() {
  var $, Curl, Recipe, querystring,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Recipe = require("../Recipe.js");

  Curl = require("../utils/Curl.js");

  $ = require("jquery");

  querystring = require("querystring");

  this.Greentel = (function(_super) {

    __extends(Greentel, _super);

    Greentel.name = 'Greentel';

    function Greentel(inputData, socket) {
      this.inputData = inputData;
      this.socket = socket;
      this.counter = 0;
      this.domTarget = "";
      this.req = {
        'insecure': true,
        url: "https://www.greentel.dk/index.php?ajax=true",
        data: {
          up_ajax_action: "do_address_check",
          cpr: inputData["dob"] + '' + inputData["cprList"][0],
          fullname: inputData["lastName"]
        }
      };
    }

    Greentel.prototype.updateCPR = function() {
      return this.req.data.cpr = this.inputData["dob"] + "" + this.inputData["cprList"][this.counter];
    };

    Greentel.prototype.getResponse = function(req, res, callback) {
      var cpr, msg, msg_regex;
      cpr = querystring.parse(req.data).cpr;
      if (!(res != null) || !(res.body != null)) {
        callback(cpr, "error", "Could not get response");
        return false;
      }
      if (res.body.indexOf("#address") > -1) {
        msg_regex = /\$\('#address'\).val\('(.*)'\);/.exec(res.body);
        msg = msg_regex != null ? msg_regex[1] : "";
        return callback(cpr, "success", msg);
      } else {
        return callback(cpr, "error", res.body);
      }
    };

    return Greentel;

  })(Recipe);

  module.exports = this.Greentel;

}).call(this);
