// Generated by CoffeeScript 1.3.1
(function() {
  var $, Curl, Recipe, querystring,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Recipe = require("../Recipe.js");

  Curl = require("../utils/Curl.js");

  $ = require("jquery");

  querystring = require("querystring");

  this.Lebara = (function(_super) {

    __extends(Lebara, _super);

    Lebara.name = 'Lebara';

    function Lebara(inputData, socket) {
      this.inputData = inputData;
      this.socket = socket;
      this.counter = 0;
      this.domTarget = "";
      this.req = {
        url: "https://mypage.lebara.dk/iframe/NOVcpr_iframe.asp",
        data: {
          cprok: "on",
          email: "test@ofir.dk",
          password1: "test1234",
          password2: "test1234",
          navn: inputData["firstName"] + " " + inputData["lastName"],
          cpr: inputData["dob"] + "-" + inputData["cprList"][0]
        }
      };
    }

    Lebara.prototype.updateCPR = function() {
      return this.req.data.cpr = this.inputData["dob"] + "-" + this.inputData["cprList"][this.counter];
    };

    Lebara.prototype.getResponse = function(req, res, callback) {
      var cpr, html, msg, msg_regex;
      cpr = querystring.parse(req.data).cpr;
      if (!(res != null) || !(res.body != null)) {
        callback(cpr, "error", "Could not get response");
        return false;
      }
      html = res.body;
      msg_regex = /alert\('(.+)'\)/.exec(html);
      msg = msg_regex != null ? msg_regex[1] : "";
      html = res.body;
      if (html.indexOf("NOVBetal") > -1) {
        return callback(cpr, "success", "");
      } else {
        return callback(cpr, "error", msg);
      }
    };

    return Lebara;

  })(Recipe);

  module.exports = this.Lebara;

}).call(this);
