// Generated by CoffeeScript 1.3.1
(function() {
  var app, callme, express, inputDebugger, io;

  callme = require("./recipes/Callme.js");

  express = require("express");

  app = express.createServer();

  app.listen(3000);

  io = require("socket.io").listen(app);

  io.set('log level', 0);

  inputDebugger = require("./utils/inputDebugger.js");

  GLOBAL.debug_mode = true;

  app.use(express.bodyParser());

  app.get("/*.html", function(req, res) {
    return res.sendfile(__dirname + "/pages/" + req.url);
  });

  app.get("/js/*", function(req, res) {
    return res.sendfile(__dirname + req.url);
  });

  app.get("/css/*", function(req, res) {
    return res.sendfile(__dirname + req.url);
  });

  app.get("/images/*", function(req, res) {
    return res.sendfile(__dirname + req.url);
  });

  app.get("/", function(req, res) {
    return res.sendfile(__dirname + "/pages/index.html");
  });

  io.sockets.on('connection', function(socket) {
    return socket.on("setInputData", function(inputData) {
      var recipe;
      recipe = new callme.Callme(inputData, socket);
      return recipe.prepareRequest(function() {
        return recipe.bruteForce();
      });
    });
  });

}).call(this);
