// Generated by CoffeeScript 1.3.1
(function() {
  var Curl;

  Curl = require("./utils/Curl.js");

  this.Recipe = (function() {

    Recipe.name = 'Recipe';

    function Recipe() {}

    Recipe.socket = null;

    Recipe.domTarget = "";

    Recipe.counter = 0;

    Recipe.completed = false;

    Recipe.req = {
      data: {},
      settings: {
        formatting: {}
      }
    };

    Recipe.settings = {};

    Recipe.inputData = {
      cprList: {}
    };

    Recipe.prototype.renderPreparationResponse = function(req, res, err) {
      return this.socket.emit("renderPreparationResponse", {
        req: req,
        err: err,
        res: res,
        domTarget: this.domTarget
      });
    };

    Recipe.prototype.getResponse = function(req, res, callback) {
      return console.log("Warning: An implementation of 'getResponse' must be made");
    };

    Recipe.prototype.afterGetResponse = function(cpr, status, msg) {
      if (msg == null) {
        msg = "";
      }
      if (status === "success") {
        this.socket.emit("correctCpr", {
          cpr: cpr,
          msg: msg
        });
        return this.completed = true;
      } else {
        return this.socket.emit("incorrectCpr", {
          cpr: cpr,
          msg: msg
        });
      }
    };

    Recipe.prototype.waitForClient = function(name, req, res, err, nextStep) {
      if (debug_mode === true) {
        this.renderPreparationResponse(req, res, err);
        console.log("Waiting for client: " + name);
        this.socket.emit("waitForClient", {
          name: name
        });
        return this.socket.once("next", function() {
          return nextStep(res);
        });
      } else {
        return nextStep(res);
      }
    };

    Recipe.prototype.prepareRequest = function(startBruteForce) {
      return startBruteForce();
    };

    Recipe.prototype.updateCPR = function(counter) {
      return console.log("Warning: An implementation of 'updateCPR' must be made");
    };

    Recipe.prototype.bruteForce = function() {
      var self;
      self = this;
      return Curl.scrape(this.req, function(req, res, err) {
        if (res == null) {
          res = {};
        }
        if (debug_mode === true) {
          self.renderPreparationResponse(req, res, err);
        }
        return self.getResponse(req, res, function(cpr, status, html) {
          self.afterGetResponse(cpr, status, html);
          self.counter++;
          self.updateCPR();
          if ((self.inputData.cprList[self.counter] != null) && self.completed !== true) {
            return self.bruteForce();
          }
        });
      }, this.settings);
    };

    return Recipe;

  })();

  module.exports = this.Recipe;

}).call(this);
