// Generated by CoffeeScript 1.3.1
(function() {
  var $, Curl, curlrequest, splitResponse;

  curlrequest = require("curlrequest");

  splitResponse = require("./splitResponse.js");

  $ = require("jquery");

  Curl = {
    scrape: function(req_specific, callback) {
      var curl_request, req;
      console.log("Scraping: " + req_specific.url);
      req = {
        headers: [],
        include: true,
        timeout: 10,
        'retries': 3,
        'location': 'false'
      };
      $.extend(req, req_specific);
      return curl_request = curlrequest.request(req, function(err, res_raw) {
        var res;
        if (res_raw != null) {
          res = splitResponse(res_raw);
        }
        return callback(req, res, err);
      });
    },
    getCookie: function(url, callback) {
      var curl_request, options;
      options = {
        url: url,
        include: true
      };
      return curl_request = curlrequest.request(options, function(err, res) {
        var cookie, head, regex, result;
        res = res.split("\r\n\r\n");
        head = res.shift();
        regex = /^Set-Cookie: (.*?);/m;
        result = head.match(regex);
        cookie = result[1];
        console.log("Cookie: " + cookie);
        return callback(cookie);
      });
    }
  };

  module.exports = Curl;

}).call(this);
