// Generated by CoffeeScript 1.3.1
(function() {
  var fs;

  fs = require("fs");

  this.kutils = (function() {

    kutils.name = 'kutils';

    function kutils() {}

    kutils.prototype.querystringOld = function(data) {
      var key, qs;
      qs = "";
      for (key in data) {
        qs += key + "=" + escape(data[key]) + "&";
      }
      data = qs.slice(0, -1);
      return data;
    };

    kutils.prototype.getCookie = function(cookieUrl, callback) {
      var child, command, exec;
      exec = require("child_process").exec;
      command = "curl -I " + cookieUrl;
      return child = exec(command, function(error, stdout, stderr) {
        var cookie, regex, result;
        regex = /^Set-Cookie: (.*?);/m;
        result = stdout.match(regex);
        cookie = result[1];
        return callback(cookie);
      });
    };

    module.exports = kutils;

    return kutils;

  })();

}).call(this);
