// Generated by CoffeeScript 1.3.1
(function() {
  var splitResponse;

  splitResponse = function(raw_response) {
    var location, res, status_code;
    res = {};
    raw_response = raw_response.split("\r\n\r\n");
    res.head = raw_response.shift();
    res.body = raw_response.join();
    status_code = /\d\d\d/.exec(res.head);
    if (status_code != null) {
      res.status_code = status_code[0];
    }
    location = /^Location: (.+)/m.exec(res.head);
    if (location != null) {
      res.location = location[1];
    }
    return res;
  };

  module.exports = splitResponse;

}).call(this);
