// Generated by CoffeeScript 1.3.1
(function() {
  var Utils;

  Utils = {
    splitResponse: function(raw_response) {
      var location, res, status_code;
      res = {};
      raw_response = raw_response.split("\r\n\r\n");
      res.head = raw_response.shift();
      res.body = raw_response.join();
      status_code = /\d\d\d/.exec(res.head);
      if (status_code != null) {
        res.status_code = status_code[0];
      }
      location = /^Location: (.+)/m.exec(res.head);
      if (location != null) {
        res.location = location[1];
      }
      return res;
    },
    dataUrlEncode: function(data, encoding) {
      var data_new, key;
      data_new = [];
      if (encoding === "utf8") {
        for (key in data) {
          data_new.push(encodeURIComponent(key) + "=" + encodeURIComponent(data[key]));
        }
      } else {
        for (key in data) {
          data_new.push(escape(key) + "=" + escape(data[key]));
        }
      }
      data_new = data_new.join('&');
      return data_new;
    }
  };

  module.exports = Utils;

}).call(this);
